Map<String, String> filterMap = {
  'Baby Food': 'SubCategory.babyFood',
  'Baked Goods': 'SubCategory.bakedGoods',
  'Eggs': 'SubCategory.eggs',
  'Milk': 'SubCategory.milk',
  'Cheese': 'SubCategory.cheese',
  'Butter, Margarine and Spreads': 'SubCategory.butterMargarineAndSpreads',
  'Cream': 'SubCategory.cream',
  'Yoghurt': 'SubCategory.yoghurt',
  'Coffee': 'SubCategory.coffee',
  'Tea': 'SubCategory.tea',
  'Juices': 'SubCategory.juices',
  'Soft Drinks': 'SubCategory.softDrinks',
  'Others': 'SubCategory.others', //Beverage others
  'Canned': 'SubCategory.canned',
  'Rice': 'SubCategory.rice',
  'Pasta': 'SubCategory.pasta',
  'Noodles': 'SubCategory.noodles',
  'Cereal': 'SubCategory.cereal',
  'Condiments': 'SubCategory.Condiments',
  'Baking Needs': 'SubCategory.bakingNeeds',
  'Oil': 'SubCategory.oil',
  'Desserts': 'SubCategory.desserts',
  'Meat': 'SubCategory.meat',
  'Seafoods': 'SubCategory.seafoods', //frozen seafood
  'Fruits': 'SubCategory.fruits',
  'Vegetables': 'SubCategory.vegetables',
  'Chicken': 'SubCategory.chicken',
  'Pork': 'SubCategory.pork',
  'Beef': 'SubCategory.beef',
  'Lamb': 'SubCategory.lamb',
  'Seafood': 'SubCategory.seafood',
  'Others ': 'MainCategory.others', // others others
  'Halal': 'DietaryNeeds.halal',
  'Kosher': 'DietaryNeeds.kosher',
  'Contains Lactose': 'DietaryNeeds.containsLactose',
  'Contains Nuts': 'DietaryNeeds.containsNuts',
  'ContainsSoy': 'DietaryNeeds.containsSoy',
  'None': 'DietaryNeeds.none',
};
